### ISSUE TITLE
Trouble adding database (Active Record)

### ISSUE THREAD

**Issue by frigidplatypus** [neverstopbuilding/sinatra-boilerplate#1]
I'm trying to get ActiveRecord working with it, but I can't get the migration to run.  I have included the necessary gems and created a database.yml file in the config directory.  I've also added register Sinatra::ActiveRecordExtension to the App module.

This is my first Sinatra project. Although I have completed a few tutorials, I'm still unfamiliar with much of the expected layout for Sinatra.

**Comment by jasonrobertfox** [comment]
Did you install this extension: https://github.com/janko-m/sinatra-activerecord 

Are you doing this with sqlite to ensure there are no local db glitches? (at least at first to narrow things down)

**Comment by jasonrobertfox** [comment]
I added a feature branch with the steps I took to run a migration, I'll close this, but feel free to re-open if you have further issues. Best of luck!
